#cloud-config
hostname: nextcloud
timezone: US/Pacific
#apt_upgrade: true
byobu_by_default: system
ssh_import_id: [joe]
#apt_sources:
# - source: "ppa:smoser/ppa"
swap: # only works on cloud-init 0.7.6 and later, trusty 14.04.5 is on 0.7.5 :-/
   filename: /swap.img
   size: "auto" # or size in bytes
   maxsize: 2147483648  # 8G should work, see https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1410824
groups:
  - joe: [joe]
users:
  - name: joe
    gecos: joe
    shell: /bin/bash
    primary-group: joe
    groups: [users, root, kvm, sudo, adm, audio, cdrom, dialout, floppy, video, plugdev, dip, netdev]
    lock-passwd: false
    passwd: $(echo '$6$rounds=4096$9HeOrRyXEKcTYA5h$mjWahfdV6X.lIiyDwRc/6hXv.7UJCH55XZbHgOOTG3yRh/3vOg5iEukKwYV8kURYtE.GuE/SGI0sUCSAqAgkS.')
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+xUBBvQ7+5WiKLSsBUrIbqyecadH+FFSJzrvA43hxM+z1LP5G0CnMHFVIYF68b58rzPvWurYshCRwOf6Z0ZOc0IAqyOxRQeIG6hphT5TfL+gB+h/BJ+YaWxNR0s7EJYr/2hWUP0j1xJ6EFt1EUH9p5vi4tRo1NcX7syxQUmedtkLrOgM7p5wAbcNGkjog8SmMyHyMZD5yQPt7kbkz2qUmZzf2CNR4aUZEoJnvyLoXDrz1OxZPklcjeXVUH7w91WKPIrTm+lt4xOn0XuCqmHzIlNixyHTBOrdoDuRbejhn/UOFswb3YFRMLczK6f3N+UqqpV9PAErK9QGOAyEjLRHZ root@mintstudio-maya
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvYqSpJvAKMqxSa9Mzhdw7pFk/UOzEOith8UolvC5HpeRieZFwPdXeEDbsVSXlzQqy0v1i226W8+CPX9JX82VWI2RZIkB3sJq3AEELO3pDbDe/Uc1WsTzbN6QUBlpl2OvZB0bBvkGbbATUU2xXefDV/g3ma4k1HkiQIAB6Ymw6XM8+5iznhx8ERsUUE9V9NGc52ujAr4Sz5E+wgLxZXWKW25IiPfAMOHvlEzfiL4S3Q8YruSy337C54ttf8VFwBHcotzybhOIUEqCqsAc70RLlhNpafNLx/sJD/yJ+R3AO0z6Brm8eVeax56gSs4eIdY23tufX2drL8ZnY1LNNhdV9w== joe@STUDIO
    sudo: ALL=(ALL) NOPASSWD:ALL
package_update: true
package_upgrade: true
#salt-minion:
#  - see https://github.com/number5/cloud-init/blob/master/doc/examples/cloud-config-salt-minion.txt
packages:
  - mc
  - python-pip
  - unp
  - git
  - docker.io
write_files:
  - path: /home/joe/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    content: |
      network: {config: disabled}
  - path: /home/joe/etc/network/interfaces.d/50-cloud-init.cfg
    content: |
      # This file is generated from information provided by
      # the datasource.  Changes to it will not persist across an instance.
      # To disable cloud-init's network configuration capabilities, write a file
      # /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
      # network: {config: disabled}
      auto lo
      iface lo inet loopback
      # JJW from cloudinit
      #auto ens3
      #iface ens3 inet dhcp
  - path: /home/joe/etc/network/interfaces.d/40-ens3-static-ip.cfg
    content: |
      auto ens3
      iface ens3 inet static
        address 216.172.134.15
        #network 216.172.134.0
        netmask 255.255.255.128
        #broadcast 216.172.134.255
        gateway 216.172.134.1
        dns-nameservers 72.13.81.2 72.13.91.2 8.8.8.8 4.2.2.1 4.2.2.2 4.2.2.3
      local-hostname: $host
  - path: /root/.ssh/id_rsa_eracks-deploy
    content: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAqFNOOZcCHcA0uOFLg/8voZB3L1t4p37l7I0Xv774efJYDXgr
      wKRJfoqsDaVx8lGjkHmkGgTOp0oPmG/cs10rQZtvBl6z2ereR8tXSb6XYoC7CV4m
      5+VfQMP3z4kmqwlKgX6mlGLNDY3o1mj0jxwNDAQ9h5ncr1zVmP23zrtbj0kXYvxc
      bKUTtwDrbOhksOh9hZcAgGg6APMuFaqdz0iZQrdpnES4Tqd4C8Gn336cixEN7TIM
      hHWGmqhhqqndez1y5JyuT9DwsttsAc1EC3V2EJrfZLJEOeRxqkncT2tAUXNwEBGG
      rE8EYDzJ7YD72zqk0sAsOGRZIq+lOmXrC2J8fwIDAQABAoIBADJZMLXTMIPboSmH
      4kGqTAIEp1HYB3/6WiXmkir9oW9AiQwGXPfzbDRYoFw4l5vGxakKaYaK15F8equ7
      EgXooW6vYodCPoO5WCGbdhGN29RP8yI7MmH83wANXguK17EjR1DypDsQTot2XiX8
      IOLJnjFw90KfSD6AAzgO9DL3Icz6sLmY/dAqOIVT6dtmkO3xmutjP9bi7/4FGYBC
      tG+LooPNDFvAo6WHxVt9MItLPmpdd8vWx/Ev5KOdJ5oBAGaulrkgA79b/szYJ/zA
      lvX7IT4rfaadnNWxhG2hJLGCWDP5VhfqDzEsAKKkrty/zq5Bw8ug7xu4nvngRU38
      5+1HvYkCgYEA08GIeYb7nwCm8bj5pl6nb17DaQTQ9iukj8AlGJNiWi6Qycd41vFF
      0AKner1XzBC/bUl3o/AnPfDv5JdSfspTg1fsFChJ7eI1OX/2fP8cU7LWMVQb5CZq
      q4l0GbBhVV0OBGM3NayHnemfIWq2S7qyn9yybAIAuE2alZ2d1TQ3xisCgYEAy36+
      tdc7JhNXLaX61PxHO+yh5f45qHSCy93sKChZTCHbD8OzsH60AmORxbKxo0JB0t/Y
      ZTXgbpE5aAxSE1tFg8ngMQ/at/LWvZopKKvq7K0HOBLDzW4Wy+YFl4scIEjN0K9f
      CTJNcVH3rpPqrW+gD4wK3kDQYFo7HPtQh3q87P0CgYBGR4o7A1DJodbGjSTWUb3y
      WZozZbTQrwVr7FKjiG7xDVlijsCNXgBUnDznoKXeBYTzCZoan972UNvdm1d220HC
      atDgk8qNmDEgB1dQfv7wzH8IWijznMh0bCdLS13SjhLT4/Xz63ILN/lnhto/4hPc
      uMvCyxtgD+mJVImItE76hwKBgFXpCHKUjzAf8iofbKoGZ7xwxljm30izB5Ux98Vs
      Y2a01FrvcCkPFMf9aUlhi4U1L7zrK9xuxnVncijvKqdpXQuqaq/L1bbbGrWpI787
      9U4+LlIJ+gf8djtWvP2hiRpIIjv8Dc9AIVm6FSrq36Sg/54QrXXvPwmujk5J+1F3
      C9OxAoGBAMLraoF23/yOfNQ3S7ooz1WcF3Ae7TCXsoTnf8hNQ3VvZN0+ehgZYXl/
      SEe63pluyqG96HI+O7Eknh7MokdXGzKhL+9F+GX3z0NvLh+mNCzi8XJajfVvcid6
      3pzWkdilhJ/o33XivfNMAOonyK+fMWO9Mxg4dMBz7SPQy4DWfa2M
      -----END RSA PRIVATE KEY-----
  - path: /root/.ssh/id_rsa_jjw-salt-deploy
    content: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIJKwIBAAKCAgEA9bAuyHsdret0U8ldzxDseQRr8kxrEAg+JqL4uFLNDwQwKB7u
      w/R/7IkQvYUYl/Z52ycrM2h9quWWrMC+1SWLs+XvuX1YayY83+vUIbYXREmk0l3B
      49RUAloO/3+Y9z8Fz4whthEKlr9TBSa7cp0g57OinxgkgFDHfRjKpoiLSyTtcRCM
      dMeghz5HLpPSjRJnWWZ1TlCZbrX+osY3ve30gD2UIwD/fKei9fmyqbS+8562bIPw
      YXVHkziHxatSbzdXV9DNWFBR5xfOY798r973SEavXjG7UBDIOH3FSZWht7GgokPv
      vN3w106HQRv3L3RSHVBXAX9Ml7Rj0SDInpaeKYlACRL6DsSKoV93DgSq3p8/U9a4
      qvPGF+Xl0MVkJB0HNLRSwP/J6FfdhAdFC0OM0qkcesyVxHKqEfsphF5N43vwXBhn
      WnS/vN3GMt6i01d+ddo40yf9lMp/Zm4G/KCV/alLtc2aIqsutNeGcliwDUhv54Jz
      vut+Nb6h2dOktuDN3BwQl52MrWoVVS8XNTkprnDGFypqeMApl5yt+NBE6vKxBZry
      ianNqfJQY6YhEy/8ru6vjkBFmE0o4D1NLl3P+EjBf/l+h6OxSOE7vEok1RpcDIHI
      6AekKp6UJ+7o4yVdAvDhhWI08hmfyvEM/IgPqQ4n+9lQrLvkHu5X2IgSA6cCAwEA
      AQKCAgEAmn9cK/4fv8qcsEOklh3SVpeNOiUL/lzwmGNLfL207Yh4sAIjq14JQ7k9
      qbAUsxrvrfyHkiBXRixx/9iFKIwfudUSVtaXz2mQRk+KaliTcQHOf+stjhNrcL8p
      R0n56yDaipVYbaFxwzI1BrxAi+Z7VrkDvn/0FCy4BdadOPQMhAiIt9zsNlOCgwmK
      waN7d/LmwrVHdyQAGDqiEcIMM4d7hVkz2n86Ki1QsNWAoG9k1NYtaTfe5apWhCG8
      X3VItV9bsYFAYBTCLEwwIVG9GutfHTg190nWvJaREdUlRwytUVKF7QRDscTvOrXL
      IApx+olvSbfHvs1KYOuzCUNQZUnZ0pFi4SOI3soZU7hiD1vyQBArzVYGIsFzYK1A
      LEpWYGwVH9R7j8fBoZARg1QgIkrvfdGzF155f3z8HzezXrURfvWnGi6fKEz+eOlY
      ep1zxqeB5JtxRhu11OgNjHU7hcDYrK033XUydCQzpiZmNYGjQvIs0XR/zJ5Kkskd
      r2Rb/IUdxVMIZfMVyjrAVQeJScO1d7Pr+a9W3OdX2IChLjrf6kKngyd/IfIYT7mb
      fLLgU3P3WzYYbU1MelnPvfG2eeh6hldfHJdRppVDzQUhy3PbQoZ098pP/Wq3qqOV
      4UTtEbmtU3jj1jGd0OsghdRrUrMqfLGa8qh4A78ZAC4oSqrLLUECggEBAP7sLE3l
      6FWjArbOkeQLVRF4swmYXTnLIhbxx3whQqnVy1Js6BGlo/4SVfTKPHIeRDwdtpAM
      1EcoQNb9A+GwhTxueUmMe72pc3tL4gcH0PvXg7bWB9jYcN9UZc0ZU/inFoNzCBDW
      ykcgWZxxMOAXKBx4k/6qs0ESxTAwUFY4sMo54GPc2A9SAeJ5c4wNp40p4SQAW6BP
      zoS3/gHb4cHJelw+DwSBh1YmPmNR2u1obrONVFP02+a4Wc8O69APb/J9JYH6kurx
      sYFUlFrF/QCcEC6U+LtcSWqRZ4Dk2kTM6Dr61uTvjAqj0mMhN8H+2ksd0UQeeGub
      SkdloH4YhzBt1ukCggEBAPa6BKJt6IugmGlch17nqyHQ4XEx8LOOduKm2fyKpZpR
      UN+HWiO6aPcB2O+MSQWmQklojxqDiL2isD6rblIf9uoFOptpv2gnxGdp6ru8rSli
      C0Z1WGjv0IUbBceQ1hMCX6UJFs8s4zhZ7T6iSeUsqE/r375qsa5mdqu142yBQzrq
      SXxvIHZtX/da+2d232mpgvLaRWujX1RJRipHDXcZompChmJY/2/Xadtncv2Q+Ncc
      C+3rc1Om43acAZYvyDcqrX52fv5pEdLi3ZEgcYFmCwEMyMp5yk2H6HDlBH9CIP05
      N4MkJWMSMGEitYqic6WLM0aZGnP6bvVr1pOTt+RjjA8CggEBANRZZ458NU0gvOIK
      sPyFdBdZs8oKYZ4C2CLExKdiDWXr8bJ3hdktYa4DGBcRX8iv7acmGS1lgm7D2T89
      BD68DECKxf2+SFV1Ef1i+KVinXMr00w6fc7kfSGL7EEtGAXJKbfV2qIsSdN13y+y
      GkSRBZix2JYLG8bZG+lIVaN9Fcde7sxA6rnYVjmRce74cNnmSOT0Z17jG+TyX2St
      BSGn84VjLJ9URqg8szuItBWPKKfo0pYdIhDPAAC7LTPjqB0Womfjkv6i1nolOm9i
      /Z3EYrZq4ccw2PcsqEt2V1t4VPrMeLW71awHSvnIcennoW9xJyDXQPhiIz3WKhrf
      071DwgECggEBANifyJPoliWJ0menov+TvnCJWnctVt3/9qfXwUr3XKEaRjyMNXtr
      Ht/I0nS4oiCAsnCLiiHIXRXLMp1DnTAj+oHMJ4HunezQBaSanUtKRGsyNx4cx4wT
      CuzjJfbrVtoH2nwnd8xc5/9BDYlRqjm6NOk++wrP2MN8GTN4Fn7dG28t52mGlGUG
      cRzX2CYme8/k0iFxvUPdhESXtTBHhC4O5sgPMrhE1bmX08ycjpzNXX5YlKzHblGD
      FPG91bLMryioov2HAsdS7yBOqiTS7HWlZ4H7fIwx1IqwCkic+47UO+y5AOF2qhDL
      FokilWxsZ8dwaYvRvyUXO7blgNe/+dRgBscCggEBAMnnRv4DFuAYvFGLyYRZW6DJ
      fRMZQBxl/8sculnAy9sAg95HiMbcO2ON2AGKKPo5DGM/8BXcQdUAd/np7i2n2/3W
      dirFEMIC23qAOpPh1VPBpSWhxveK5y4AYeQWF+vwaaFntaak4E0Wl2HnXoAgNNPQ
      TLKxt1LIzJrECx2+WE/s2/jNSsc4AhGMeClWLb0ToUA9dGmlQVOP3PxydZJJpCNS
      xc1B+EjGv85XBRYZBU9wXxxY+RJ109nCp7Rq0kkxDXd9jKj8mtDY7D0Er5g5ECqM
      fpmDSMWK9zBEQCClR90l1GqY4yVMJmS+Vd8KxLbXdDGQGZLVy5s7uNgWGLIvuO8=
      -----END RSA PRIVATE KEY-----
  - path: /var/lib/cloud-compose/docker-compose.yml
    content: |
      version: '3'
      services:
        hello-world:
          image: tutum/hello-world
          restart: always
          ports:
            - 8080:80
  - path: /root/cloud-init-runcmd.sh
    permissions: '0770'
    content: |
      cd /root
      echo IN ROOT INSTALLING SALT
      pwd
      id
      ifdown ens3; ifup ens3
      ifconfig -a
      curl -L https://bootstrap.saltstack.com -o install_salt.sh
      sudo sh install_salt.sh -U -P -A desqhost.com -i $host
      echo SETTING UP SALT KEYS AND REPOS
      chmod 400 /root/.ssh/id_rsa_jjw-salt-deploy
      chmod 400 /root/.ssh/id_rsa_eracks-deploy
      echo "cp is necessary here due to write_files bug, it's done before user creation, and creates the joe home dir owned by root"
      cp /root/.ssh/id_rsa_eracks-deploy /home/joe/.ssh/id_rsa_eracks-deploy
      echo tail -f /var/log/cloud-init-output.log >> /home/joe/.bash_history
      echo less /var/log/cloud-init-output.log >> /home/joe/.bash_history
      ssh-keyscan -H github.com >>/root/.ssh/known_hosts
      sudo -u joe ssh-keyscan -H github.com >>/home/joe/.ssh/known_hosts
      ssh-agent bash -c 'ssh-add .ssh/id_rsa_jjw-salt-deploy && git clone -q git@github.com:jowolf/jjw-salt-master.git'
      #echo SETTING UP ERACKS REPO
      #sudo -iu joe ssh-agent bash -c 'ssh-add .ssh/id_rsa_eracks-deploy && git clone -q git@github.com:jowolf/eracks11.git'
      echo SETTING UP TLG REPO
      git clone -q git@github.com:jowolf/tlg.git
      chown -R joe:joe /home/joe
      echo APPLYING SALT STATES
      cd jjw-salt-master/salt
      salt-call --local --file-root=. state.apply joe
      salt-call --local --file-root=. state.apply salt-minion
      salt-call --local --file-root=. state.apply hostname-from-minion-id
      echo tail -f /var/log/cloud-init-output.log >> /home/joe/.bash_history
      echo SETTING UP NEXTCLOUD
      docker pull filcuc/nextcloud:latest
      docker create --name nextcloud-data filcuc/nextcloud:latest /bin/true
      docker run -ti --rm --volumes-from nextcloud-data --name nextcloud-app -p 80:80 -p 443:443 filcuc/nextcloud:latest setup --nc-db='pgsql' --nc-db-user='nextcloud' --nc-db-pass='nextcloud' --nc-db-name='nextcloud' --nc-url='https://download.nextcloud.com/server/releases/nextcloud-9.0.53.tar.bz2' --nc-archive='nextcloud-9.0.53.tar.bz2' --nc-admin-name='admin' --nc-admin-pass='admin' --nc-dir-name='nextcloud' --ng-root='/var/www/' --ng-user='www-data' --ng-domain='jw.vc' --le-email='j@jw.vc'
      exit

      reboot
      echo APPLYING ERACKS DEPLOY SLS STATES
      cd /home/joe/eracks11
      #sudo -u joe git checkout brahms
      cd conf/
      ./deploy.sh prod
      # move db blast to here
      # call salt fm here for at least staging, prod
runcmd:
  - cd /root
  - echo RUNNING RUNCMD SCRIPT
  - bash cloud-init-runcmd.sh
  - touch DONE
