section: userdata.yaml
action:
  save: $workdir
content: |
  #cloud-config
  hostname: $vmname
  timezone: US/Pacific
  #apt_upgrade: true
  byobu_by_default: system
  ssh_import_id: [$user]
  #apt_sources:
  # - source: "ppa:smoser/ppa"
  swap: # only works on cloud-init 0.7.6 and later, trusty 14.04.5 is on 0.7.5 :-/
     filename: /swap.img
     size: "auto" # or size in bytes
     maxsize: 2147483648  # 8G should work, see https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1410824
  groups:
    - $user: [sys, users]
  users:
    - name: $user
      gecos: $user
      shell: /bin/bash
      primary-group: $user
      groups: [users, root, kvm, sudo, adm, audio, cdrom, dialout, floppy, video, plugdev, dip, netdev]
      lock-passwd: false
      passwd: '$6$rounds=4096$9HeOrRyXEKcTYA5h$mjWahfdV6X.lIiyDwRc/6hXv.7UJCH55XZbHgOOTG3yRh/3vOg5iEukKwYV8kURYtE.GuE/SGI0sUCSAqAgkS.'
      ssh-authorized-keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+xUBBvQ7+5WiKLSsBUrIbqyecadH+FFSJzrvA43hxM+z1LP5G0CnMHFVIYF68b58rzPvWurYshCRwOf6Z0ZOc0IAqyOxRQeIG6hphT5TfL+gB+h/BJ+YaWxNR0s7EJYr/2hWUP0j1xJ6EFt1EUH9p5vi4tRo1NcX7syxQUmedtkLrOgM7p5wAbcNGkjog8SmMyHyMZD5yQPt7kbkz2qUmZzf2CNR4aUZEoJnvyLoXDrz1OxZPklcjeXVUH7w91WKPIrTm+lt4xOn0XuCqmHzIlNixyHTBOrdoDuRbejhn/UOFswb3YFRMLczK6f3N+UqqpV9PAErK9QGOAyEjLRHZ root@mintstudio-maya
        - $key
      sudo: ALL=(ALL) NOPASSWD:ALL
  package_update: true
  package_upgrade: true
  #salt-minion:
  #  - see https://github.com/number5/cloud-init/blob/master/doc/examples/cloud-config-salt-minion.txt
  packages:
    - mc
    - python-pip
    - python-virtualenv
    - unp
    - git
    - docker.io
  write_files:
    - path: /usr/local/bin/hostmounts.sh
      permissions: '0755'
      content: |
        #!/bin/bash

        for f in /sys/bus/virtio/drivers/9pnet_virtio/virtio*; do
          echo VALID MOUNT TAGS >> 6_MOUNTING_HOSTSHARES
          echo $f >> 6_MOUNTING_HOSTSHARES
          mtag=`cat $f/mount_tag`
          echo $mtag >> 6_MOUNTING_HOSTSHARES
        done

        n=0
        for p in $hostshares; do    # for f in a b c d e; do
          echo MAPPING $n $p >> 6_MOUNTING_HOSTSHARES
          mkdir -p /home/$user/$p
          echo mount -t 9p -o trans=virtio,version=9p2000.L,uname=joe hostshare$n /home/$user/$p >> 6_MOUNTING_HOSTSHARES
          mount -t 9p -o trans=virtio,version=9p2000.L,uname=joe hostshare$n /home/$user/$p >> 6_MOUNTING_HOSTSHARES
          mount >> 6_MOUNTING_HOSTSHARES
          (( ++n ))
        done
    - path: /home/$user/go.sh
      permissions: '0770'
      content: |
        #!/usr/bin/python
        import sys, os, fcntl, termios
        tty = os.ttyname(sys.stdin.fileno())
        with open (tty, 'w') as fd:
          for c in ". env/bin/activate\n":
            fcntl.ioctl (fd, termios.TIOCSTI, c)
    - path: /root/cloud-init-runcmd.sh
      permissions: '0770'
      content: |
        cd /home/$user

        echo 1_DOING_KEYSCAN
        touch 1_DOING_KEYSCAN
        sudo -u $user ssh-keyscan -H github.com >>/home/$user/.ssh/known_hosts
        echo DONE >> 1_DOING_KEYSCAN

        echo 2_PRECONFIG_BASH_HISTORY
        touch 2_PRECONFIG_BASH_HISTORY
        echo tail -f /var/log/cloud-init-output.log >> /home/$user/.bash_history
        echo less /var/log/cloud-init-output.log >> /home/$user/.bash_history
        echo less /var/log/cloud-init.log >> /home/$user/.bash_history
        echo sudo netstat -antp >> /home/$user/.bash_history
        echo DONE >> 2_PRECONFIG_BASH_HISTORY

        # now used only for salt
        echo 3_CLONE_GIT_REPO
        touch 3_CLONE_GIT_REPO
        #ssh-agent bash -c 'ssh-add $git_repo_key && git clone -q $git_repo' >> 3_CLONE_GIT_REPO
        # do them separately so we can do pub repos w/o key
        ssh-agent bash -c 'ssh-add $git_repo_key >> 3_CLONE_GIT_REPO 2>&1'
        ssh-agent bash -c 'git clone -q $git_repo >> 3_CLONE_GIT_REPO 2>&1'
        echo DONE >> 3_CLONE_GIT_REPO

        echo 4_SETTING_UP_DOCKER_COMPOSE
        touch 4_SETTING_UP_DOCKER_COMPOSE
        # sudo apt-get install python-virtualenv
        virtualenv -v env
        #./go.sh
        . env/bin/activate
        pip install docker-compose >> 4_SETTING_UP_DOCKER_COMPOSE 2>&1
        echo DONE >> 4_SETTING_UP_DOCKER_COMPOSE

        echo 5_CHOWN_$user
        touch 5_CHOWN_$user
        sudo chown -R $user:$user /home/$user
        echo DONE >> 5_CHOWN_$user

        echo 6_MOUNTING_HOSTSHARES

        hostmounts.sh

        #for f in /sys/bus/virtio/drivers/9pnet_virtio/virtio*; do
        #  echo VALID MOUNT TAGS >> 6_MOUNTING_HOSTSHARES
        #  echo $f >> 6_MOUNTING_HOSTSHARES
        #  mtag=`cat $f/mount_tag`
        #  echo $mtag >> 6_MOUNTING_HOSTSHARES
        #done

        #n=0
        #for p in $hostshares; do    # for f in a b c d e; do
        #  echo MAPPING $n $p >> 6_MOUNTING_HOSTSHARES
        #  mkdir -p /home/$user/$p
        #  echo mount -t 9p -o trans=virtio,version=9p2000.L,uname=joe hostshare$n /home/$user/$p >> 6_MOUNTING_HOSTSHARES
        #  mount -t 9p -o trans=virtio,version=9p2000.L,uname=joe hostshare$n /home/$user/$p >> 6_MOUNTING_HOSTSHARES
        #  mount >> 6_MOUNTING_HOSTSHARES
        #  (( ++n ))
        #done

        echo DONE >> 6_MOUNTING_HOSTSHARES


        if test -e startup.sh; then
          echo 7_DOING_STARTUP_COMMANDS
          sudo -u $user sh -c "sh startup.sh >> 7_DOING_STARTUP_COMMANDS 2>&1"
          echo DONE >> 7_DOING_STARTUP_COMMANDS
        fi

        #echo DOING_FIRSTBOOT_COMMANDS
        #sudo -u $user sh -c "sh startup.sh >> DOING_FIRSTBOOT_COMMANDS 2>&1"
        #echo DONE >> DOING_FIRSTBOOT_COMMANDS
        exit
    $file1
    $file2
    $file3
    $file4
    $file5
    $file6
    $file7
    $file8
  comment: |
    comments ANYWHERE in the runcmd list break the module - sheesh.
    echo Wow! comments break the runcmd of cloudinit: \# $cmd2 $cmd3 etc
  runcmd:
    - cd /root
    - echo RUNNING_RUNCMD_SCRIPT
    - touch RUNNING_RUNCMD_SCRIPT
    - bash cloud-init-runcmd.sh >>RUNNING_RUNCMD_SCRIPT
    - echo DONE >>RUNNING_RUNCMD_SCRIPT
---
#section: metadata.yaml
#action:
#  save: $workdir
#content: |
#  #dsmode: local
#  instance-id: $vmname;
#  network-interfaces: |
#    auto ens3
#    #iface ens3 inet dhcp
#    iface ens3 inet static
#      # for local VMs, at least on LGram, this is the lxc bridge nw
#      address 10.0.3.$iplast
#    #  address 216.172.133.$iplast
#    #  #network 216.172.133.0
#      netmask 255.255.255.0
#    #  #broadcast 216.172.133.255
#    #  gateway 216.172.133.1
#      gateway 10.0.3.1
#      dns-nameservers 72.13.81.2 72.13.91.2 1.1.1.1 8.8.8.8 4.2.2.1 4.2.2.2 4.2.2.3
#  local-hostname: $vmname
#---
section: download.sh
action:
  command:
    download:
        help: Download the bootable image defined in declarations
content: |
  # download.sh generated $date by eVirt

  # Convert python-replaced variable into bash var:
  #   could call it 'baseimage', but that has two meanings -
  #   the base image itself, or the basename of the image url
  #${image="$image"}
  image="$image"

  # For now, assumes .img - see notes / todo
  fname=`basename $image`

  echo IMAGE FILENAME $fname

  # Check for remote / downloadable:
  #if test ${image:0:4} != http; then {
  #  echo Image $image is local - not downloading
  #  exit
  #} fi

  # download image as basename
  if ( ls $fname || ls $installdir/$fname ); then
    echo DOWNLOADED BASE IMAGE PRESENT - NOT DOWNLOADING!
  else
    echo Downloading: $image
    wget -O $fname $image
  fi
---
section: build.sh
action:
  command:
    build:
        help: Build / make new VM from ev.yaml using cloud-init, userdata, metadata, and declarations.
        #metavar: make-new-vm
content: |
  # build.sh - generated $date by eVirt
  # copy downloaded image as $vmname.$ext

  # For now, assumes .img - see notes / todo
  fname=`basename $image`

  if ( ls -l $vmname.img ); then
    echo VM IMAGE PRESENT - NOT COPYING!
  else
    # copy from image location:
    #echo $image
    #echo $fname
    #echo test -e $fname

    if test -e $fname; then
      echo Copying from downloaded base image...
      cp $fname $vmname.img
    elif test -e $installdir/$fname; then
      echo Copying from downloaded base image in eVirt Install dir...
      cp $installdir/$fname $vmname.img
    else
      echo No downloaded image file present - $image
    fi
  fi

  if test $ext == qc2; then {
    qemu-img convert -O qcow2 -c $vmname.img $vmname.qc2
  } fi

  qemu-img resize $vmname.$ext $size
  if test -e $workdir/metadata.yaml; then
    cloud-localds $workdir/cloudinit.img $workdir/userdata.yaml $workdir/metadata.yaml
  else
    cloud-localds $workdir/cloudinit.img $workdir/userdata.yaml
  fi
  qemu-img convert -O qcow2 -c .evirt/cloudinit.img .evirt/cloudinit.qc2

