#cloud-config
#password: passw0rd
#chpasswd: { expire: False }
#ssh_pwauth: True
groups:
  - joe: [joe]
users:
  #- default
  - name: joe
    gecos: joe
    shell: /bin/bash
    primary-group: joe
    groups: [users, root, kvm, sudo, adm, audio, cdrom, dialout, floppy, video, plugdev, dip, netdev]
    # requires selinux-enabled kernel:
    #selinux-user: staff_u
    #expiredate: 2012-09-01
    #ssh-import-id: foobar
    lock-passwd: false
    passwd: $6$rounds=4096$9HeOrRyXEKcTYA5h$mjWahfdV6X.lIiyDwRc/6hXv.7UJCH55XZbHgOOTG3yRh/3vOg5iEukKwYV8kURYtE.GuE/SGI0sUCSAqAgkS.
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+xUBBvQ7+5WiKLSsBUrIbqyecadH+FFSJzrvA43hxM+z1LP5G0CnMHFVIYF68b58rzPvWurYshCRwOf6Z0ZOc0IAqyOxRQeIG6hphT5TfL+gB+h/BJ+YaWxNR0s7EJYr/2hWUP0j1xJ6EFt1EUH9p5vi4tRo1NcX7syxQUmedtkLrOgM7p5wAbcNGkjog8SmMyHyMZD5yQPt7kbkz2qUmZzf2CNR4aUZEoJnvyLoXDrz1OxZPklcjeXVUH7w91WKPIrTm+lt4xOn0XuCqmHzIlNixyHTBOrdoDuRbejhn/UOFswb3YFRMLczK6f3N+UqqpV9PAErK9QGOAyEjLRHZ root@mintstudio-maya
    sudo: ALL=(ALL) NOPASSWD:ALL
#apt_sources:
#  - source: "ppa:saltstack/salt"    # Quote the string
package_upgrade: true
packages:
  - mc
  - python-pip
  - unp
  #- salt-minion
runcmd:
  - "curl -L https://bootstrap.saltstack.com -o install_salt.sh"
  - "sudo sh install_salt.sh -U -P -A desqhost.com -i evirt2-ubuntu-example"
  - "until sudo salt-call --master desqhost.com state.highstate; do { echo Waiting for salt-master to authenticate...; sleep 10; } done
#salt_minion:  # nope - blasts default minion conf (w/docs), if .d dir specifid, doesn't have .conf ext
#  config_dir: /etc/salt/minion.d
#  conf:
#    master: desqhost.com
#    minion_id: evirt2-ubuntu-example
#system_info:
#  default_user:
#    name: joe
#    # plain_text_passwd: 'ubuntu'
#    home: /home/joe
#    shell: /bin/bash
#    lock_passwd: false
#    gecos: Joe
#    groups: [adm, audio, cdrom, dialout, floppy, video, plugdev, dip, netdev]
